#!/usr/bin/env node
/**
 * generate-cli — Build-time CLI generator for OpenClaw plugins.
 *
 * Reads a plugin's createEntry() metadata and emits a standalone CLI
 * entry point into dist/bin/<plugin-id>.js.
 *
 * Usage:
 *   generate-cli --entry ./dist/index.js --out ./dist/bin
 *   generate-cli --entry ./dist/index.js --out ./dist/bin --name my-tool
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { pathToFileURL } from "node:url";

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

function parseGeneratorArgs(): { entry: string; outDir: string; name?: string } {
  const args = process.argv.slice(2);
  let entry = "";
  let outDir = "";
  let name: string | undefined;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--entry" && args[i + 1]) entry = args[++i];
    else if (args[i] === "--out" && args[i + 1]) outDir = args[++i];
    else if (args[i] === "--name" && args[i + 1]) name = args[++i];
  }

  if (!entry || !outDir) {
    console.error("Usage: generate-cli --entry <path-to-dist/index.js> --out <output-dir> [--name <bin-name>]");
    process.exit(1);
  }

  return { entry: resolve(entry), outDir: resolve(outDir), name };
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

async function main() {
  const { entry, outDir, name } = parseGeneratorArgs();

  // Dynamic import the plugin entry
  const entryUrl = pathToFileURL(entry).href;
  const mod = await import(entryUrl);

  const createEntry = mod.createEntry ?? mod.default?.createEntry;
  if (typeof createEntry !== "function") {
    console.error(`Error: ${entry} does not export createEntry()`);
    process.exit(1);
  }

  const pluginEntry = createEntry();
  const binName = name ?? pluginEntry.id;
  const envPrefix = binName.replace(/-/g, "_").toUpperCase();

  // Compute relative path from output bin dir to the entry file
  const relativeEntry = computeRelativePath(outDir, entry);

  // Generate the CLI file content
  const cliContent = `#!/usr/bin/env node
// Auto-generated by @openclaw/cli-shared generate-cli
// Do not edit — regenerate with: npm run build
import { run } from "@openclaw/cli-shared";
import { createEntry } from "${relativeEntry}";

run(createEntry(), { binName: "${binName}", envPrefix: "${envPrefix}" });
`;

  // Write
  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, `${binName}.js`);
  writeFileSync(outPath, cliContent, { mode: 0o755 });
  console.log(`Generated: ${outPath}`);
}

function computeRelativePath(fromDir: string, toFile: string): string {
  const fromParts = fromDir.split("/").filter(Boolean);
  const toParts = dirname(toFile).split("/").filter(Boolean);

  let common = 0;
  while (common < fromParts.length && common < toParts.length && fromParts[common] === toParts[common]) {
    common++;
  }

  const ups = fromParts.length - common;
  const downs = toParts.slice(common);
  const filename = toFile.split("/").pop()!;

  let relative = "../".repeat(ups);
  if (downs.length) relative += downs.join("/") + "/";

  return (relative || "./") + filename;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
